schema_version = "1.0.0"
id = "bonsai"
version = "0.8.3-post1"
name = "Bonsai"
tagline = "A native Building Information Model authoring platform using IFC"
maintainer = "Dion Moult <dion@thinkmoult.com>"
type = "add-on"
website = "https://bonsaibim.org/"
tags = [
    "3D View",
    "Add Mesh",
    "Animation",
    "Camera",
    "Development",
    "Import-Export",
    "Lighting",
    "Material",
    "Modeling",
    "Mesh",
    "Node",
    "Object",
    "Pipeline",
    "Render",
    "Scene",
    "System",
    "User Interface",
    "UV"
]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
platforms = ["macos-arm64"]
permissions.network = "Augin / Cove.Tool integration for VR and environmental analysis"
permissions.files = "Load and save IFCs, IDS, BCF, etc from disk"
permissions.clipboard = "Copy and paste error logs"

wheels = [
    "./wheels/GitPython-3.1.44-py3-none-any.whl",
    "./wheels/MarkupSafe-3.0.2-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/aiohappyeyeballs-2.6.1-py3-none-any.whl",
    "./wheels/aiohttp-3.12.14-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/aiosignal-1.4.0-py3-none-any.whl",
    "./wheels/alembic-1.16.4-py3-none-any.whl",
    "./wheels/attrs-25.3.0-py3-none-any.whl",
    "./wheels/aud-0.8.6-py3-none-any.whl",
    "./wheels/bcf_client-0.8.3.post1-py3-none-any.whl",
    "./wheels/bidict-0.23.1-py3-none-any.whl",
    "./wheels/bonsai-0.8.3.post1-py3-none-any.whl",
    "./wheels/bpypolyskel-0.0.0-py3-none-any.whl",
    "./wheels/brickschema-0.7.6a2-py3-none-any.whl",
    "./wheels/brickschema_rdflib_sqlalchemy-0.6.0-py3-none-any.whl",
    "./wheels/bsdd-0.8.3.post1-py3-none-any.whl",
    "./wheels/certifi-2025.7.14-py3-none-any.whl",
    "./wheels/charset_normalizer-3.4.2-cp311-cp311-macosx_10_9_universal2.whl",
    "./wheels/cjio-0.9.0-py2.py3-none-any.whl",
    "./wheels/click-8.2.1-py3-none-any.whl",
    "./wheels/colorama-0.4.6-py2.py3-none-any.whl",
    "./wheels/deepdiff-8.5.0-py3-none-any.whl",
    "./wheels/defusedxml-0.7.1-py2.py3-none-any.whl",
    "./wheels/elementpath-5.0.3-py3-none-any.whl",
    "./wheels/et_xmlfile-2.0.0-py3-none-any.whl",
    "./wheels/ezdxf-1.4.2-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/fonttools-4.59.0-cp311-cp311-macosx_10_9_universal2.whl",
    "./wheels/frozenlist-1.7.0-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/gitdb-4.0.12-py3-none-any.whl",
    "./wheels/greenlet-3.2.3-cp311-cp311-macosx_11_0_universal2.whl",
    "./wheels/h11-0.16.0-py3-none-any.whl",
    "./wheels/html5lib-1.1-py2.py3-none-any.whl",
    "./wheels/idna-3.10-py3-none-any.whl",
    "./wheels/ifc4d-0.8.3.post1-py3-none-any.whl",
    "./wheels/ifc5d-0.8.3.post1-py3-none-any.whl",
    "./wheels/ifccityjson-0.8.3.post1-py3-none-any.whl",
    "./wheels/ifcclash-0.8.3.post1-py3-none-any.whl",
    "./wheels/ifccsv-0.8.3.post1-py3-none-any.whl",
    "./wheels/ifcdiff-0.8.3.post1-py3-none-any.whl",
    "./wheels/ifcfm-0.8.3.post1-py3-none-any.whl",
    "./wheels/ifcjson-0.0.1-py3-none-any.whl",
    "./wheels/ifcopenshell-0.8.3-post1-py311-none-macosx_11_0_arm64.whl",
    "./wheels/ifcpatch-0.8.3.post1-py3-none-any.whl",
    "./wheels/ifctester-0.8.3.post1-py3-none-any.whl",
    "./wheels/importlib_metadata-8.7.0-py3-none-any.whl",
    "./wheels/importlib_resources-3.3.1-py2.py3-none-any.whl",
    "./wheels/iniconfig-2.1.0-py3-none-any.whl",
    "./wheels/isodate-0.7.2-py3-none-any.whl",
    "./wheels/lark-1.2.2-py3-none-any.whl",
    "./wheels/lxml-6.0.0-cp311-cp311-macosx_10_9_universal2.whl",
    "./wheels/mako-1.3.10-py3-none-any.whl",
    "./wheels/multidict-6.6.3-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/natsort-8.4.0-py3-none-any.whl",
    "./wheels/networkx-3.5-py3-none-any.whl",
    "./wheels/odfpy-1.4.1-py2.py3-none-any.whl",
    "./wheels/openpyxl-3.1.5-py2.py3-none-any.whl",
    "./wheels/orderly_set-5.5.0-py3-none-any.whl",
    "./wheels/owlrl-6.0.2-py3-none-any.whl",
    "./wheels/packaging-25.0-py3-none-any.whl",
    "./wheels/pandas-2.3.1-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/pillow-11.3.0-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/platformdirs-4.3.8-py3-none-any.whl",
    "./wheels/pluggy-1.6.0-py3-none-any.whl",
    "./wheels/prettytable-3.16.0-py3-none-any.whl",
    "./wheels/propcache-0.3.2-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/pydub-0.25.1-py2.py3-none-any.whl",
    "./wheels/pygments-2.19.2-py3-none-any.whl",
    "./wheels/pyp6xer-1.16.0-py3-none-any.whl",
    "./wheels/pyparsing-3.2.3-py3-none-any.whl",
    "./wheels/pyradiance-1.1.4-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/pyshacl-0.25.0-py3-none-any.whl",
    "./wheels/pystache-0.6.8-py3-none-any.whl",
    "./wheels/pytest-8.4.1-py3-none-any.whl",
    "./wheels/python_dateutil-2.9.0.post0-py2.py3-none-any.whl",
    "./wheels/python_engineio-4.12.2-py3-none-any.whl",
    "./wheels/python_socketio-5.13.0-py3-none-any.whl",
    "./wheels/pytz-2025.2-py2.py3-none-any.whl",
    "./wheels/rdflib-7.1.4-py3-none-any.whl",
    "./wheels/requests-2.32.4-py3-none-any.whl",
    "./wheels/shapely-2.1.1-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/simple_websocket-1.1.0-py3-none-any.whl",
    "./wheels/six-1.17.0-py2.py3-none-any.whl",
    "./wheels/smmap-5.0.2-py3-none-any.whl",
    "./wheels/sqlalchemy-2.0.41-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/svgwrite-1.4.3-py3-none-any.whl",
    "./wheels/typing_extensions-4.14.1-py3-none-any.whl",
    "./wheels/tzdata-2025.2-py2.py3-none-any.whl",
    "./wheels/tzfpy-1.0.0-cp311-abi3-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl",
    "./wheels/urllib3-2.5.0-py3-none-any.whl",
    "./wheels/wcwidth-0.2.13-py2.py3-none-any.whl",
    "./wheels/webencodings-0.5.1-py2.py3-none-any.whl",
    "./wheels/wsproto-1.2.0-py3-none-any.whl",
    "./wheels/xmlschema-4.1.0-py3-none-any.whl",
    "./wheels/xsdata-25.7-py3-none-any.whl",
    "./wheels/yarl-1.20.1-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/zipp-3.23.0-py3-none-any.whl",
]
